dependencies:
- name: carts
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.4.21
- name: catalogue
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.3.25
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: front-end
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.3.21
- name: load-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.14
- name: orders
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.4.13
- name: payment
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.4.27
- name: queue-master
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.3.3
- name: shipping
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.4.15
- name: user
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.4.18
