dependencies:
- name: carts
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.4.37
- name: catalogue
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.3.47
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: front-end
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.3.26
- name: load-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.16
- name: orders
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.4.27
- name: payment
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.4.27
- name: queue-master
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.3.3
- name: shipping
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.4.15
- name: user
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.4.33
