dependencies:
- name: catalogue
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.3.23
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.58
- name: front-end
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.3.21
- name: load-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.1.2
- name: payment
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.4.25
- name: user
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.4.11
